# Generated by Django 4.2.6 on 2023-10-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
